[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1", features = ["full"] }
tonic = "0.7.1"
reqwest = { version = "0.11", features = ["blocking"] }
rdkafka = { version = "0.25", features = ["dynamic-linking"] }
serde_json = "1.0"
prost = "0.10"
clap = "2.26.0"
tokio-postgres = "0.7.8"

[build-dependencies]
tonic-build = "0.7.1"

[[bin]]
name = "server"
path = "src/main.rs"
