# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"\x1f\n\rRecallRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\"/\n\x0eRecallResponse\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"J\n\x10GetRatingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06itemid\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_values\x18\x03 \x03(\x01\"C\n\x11GetRatingResponse\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06itemid\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x32\x82\x01\n\x05Model\x12@\n\tGetRating\x12\x17.model.GetRatingRequest\x1a\x18.model.GetRatingResponse\"\x00\x12\x37\n\x06Recall\x12\x14.model.RecallRequest\x1a\x15.model.RecallResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECALLREQUEST']._serialized_start=22
  _globals['_RECALLREQUEST']._serialized_end=53
  _globals['_RECALLRESPONSE']._serialized_start=55
  _globals['_RECALLRESPONSE']._serialized_end=102
  _globals['_GETRATINGREQUEST']._serialized_start=104
  _globals['_GETRATINGREQUEST']._serialized_end=178
  _globals['_GETRATINGRESPONSE']._serialized_start=180
  _globals['_GETRATINGRESPONSE']._serialized_end=247
  _globals['_MODEL']._serialized_start=250
  _globals['_MODEL']._serialized_end=380
# @@protoc_insertion_point(module_scope)
