[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features=["rt", "rt-multi-thread"]}
tonic = "0.7.1"
reqwest = { version = "0.11"}
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.7"
prost = "0.10"
serde = { version = "1", features = ["derive"] }
futures = "0.3.0"